from predict_alliance import predict_alliance
from unittest.mock import patch
import server
import pytest


def test_predict_alliance():
    with patch("server.Server.ask_calc_all_data", return_value=False):
        test_server = server.Server()
    fake_obj_team_data = [
        {
            "team_number": "1678",
            "matches_played": 5,
            "auto_avg_cube_low": 1.0,
            "auto_avg_cone_low": 2.5,
            "auto_avg_cube_mid": 4.5,
            "auto_avg_cone_mid": 3.5,
            "auto_avg_cube_high": 7.5,
            "auto_avg_cone_high": 6.0,
            "auto_avg_cube_total": 13.0,
            "auto_avg_cone_total": 12.0,
            "tele_avg_cube_low": 3.3,
            "tele_avg_cone_low": 2.3,
            "tele_avg_cube_mid": 3.5,
            "tele_avg_cone_mid": 2.5,
            "tele_avg_cube_high": 2.2,
            "tele_avg_cone_high": 4.3,
            "tele_avg_cube_total": 9.0,
            "tele_avg_cone_total": 8.1,
            "auto_charge_attempts": 1,
            "auto_dock_successes": 1,
            "auto_dock_percent_success": 1.0,
            "auto_dock_only_percent_success": 1.0,
            "auto_engage_successes": 0,
            "auto_engage_percent_success": 0.0,
            "tele_charge_attempts": 2,
            "tele_dock_successes": 1,
            "tele_dock_percent_success": 0.5,
            "tele_dock_only_percent_success": 0.5,
            "tele_engage_successes": 1,
            "tele_engage_percent_success": 0.5,
            "tele_park_successes": 0,
            "tele_park_percent_success": 0.0,
        },
        {
            "team_number": "1533",
            "matches_played": 5,
            "auto_avg_cube_low": 1.1,
            "auto_avg_cone_low": 2.6,
            "auto_avg_cube_mid": 4.6,
            "auto_avg_cone_mid": 3.6,
            "auto_avg_cube_high": 7.6,
            "auto_avg_cone_high": 6.1,
            "auto_avg_cube_total": 13.3,
            "auto_avg_cone_total": 12.3,
            "tele_avg_cube_low": 3.4,
            "tele_avg_cone_low": 2.4,
            "tele_avg_cube_mid": 3.6,
            "tele_avg_cone_mid": 2.6,
            "tele_avg_cube_high": 2.3,
            "tele_avg_cone_high": 4.4,
            "tele_avg_cube_total": 9.3,
            "tele_avg_cone_total": 8.4,
            "auto_charge_attempts": 1,
            "auto_dock_successes": 0,
            "auto_dock_percent_success": 0.0,
            "auto_dock_only_percent_success": 0.0,
            "auto_engage_successes": 1,
            "auto_engage_percent_success": 1.0,
            "tele_charge_attempts": 2,
            "tele_dock_successes": 0,
            "tele_dock_percent_success": 0.0,
            "tele_dock_only_percent_success": 0.0,
            "tele_engage_successes": 1,
            "tele_engage_percent_success": 0.5,
            "tele_park_successes": 1,
            "tele_park_percent_success": 0.5,
        },
        {
            "team_number": "7229",
            "matches_played": 5,
            "auto_avg_cube_low": 1.2,
            "auto_avg_cone_low": 2.7,
            "auto_avg_cube_mid": 4.7,
            "auto_avg_cone_mid": 3.7,
            "auto_avg_cube_high": 7.7,
            "auto_avg_cone_high": 6.2,
            "auto_avg_cube_total": 13.6,
            "auto_avg_cone_total": 12.6,
            "tele_avg_cube_low": 3.5,
            "tele_avg_cone_low": 2.5,
            "tele_avg_cube_mid": 3.7,
            "tele_avg_cone_mid": 2.7,
            "tele_avg_cube_high": 2.4,
            "tele_avg_cone_high": 4.5,
            "tele_avg_cube_total": 9.6,
            "tele_avg_cone_total": 8.7,
            "auto_charge_attempts": 2,
            "auto_dock_successes": 1,
            "auto_dock_percent_success": 0.5,
            "auto_dock_only_percent_success": 0.5,
            "auto_engage_successes": 1,
            "auto_engage_percent_success": 0.5,
            "tele_charge_attempts": 2,
            "tele_dock_successes": 1,
            "tele_dock_percent_success": 0.5,
            "tele_dock_only_percent_success": 0.5,
            "tele_engage_successes": 0,
            "tele_engage_percent_success": 0.0,
            "tele_park_successes": 1,
            "tele_park_percent_success": 0.5,
        },
        {
            "team_number": "2468",
            "matches_played": 5,
            "auto_avg_cube_low": 1.1,
            "auto_avg_cone_low": 2.7,
            "auto_avg_cube_mid": 4.6,
            "auto_avg_cone_mid": 3.7,
            "auto_avg_cube_high": 7.6,
            "auto_avg_cone_high": 6.2,
            "auto_avg_cube_total": 13.3,
            "auto_avg_cone_total": 12.6,
            "tele_avg_cube_low": 3.4,
            "tele_avg_cone_low": 2.5,
            "tele_avg_cube_mid": 3.6,
            "tele_avg_cone_mid": 2.7,
            "tele_avg_cube_high": 2.3,
            "tele_avg_cone_high": 4.5,
            "tele_avg_cube_total": 9.3,
            "tele_avg_cone_total": 8.7,
            "auto_charge_attempts": 1,
            "auto_dock_successes": 0,
            "auto_dock_percent_success": 0.0,
            "auto_dock_only_percent_success": 0.0,
            "auto_engage_successes": 0,
            "auto_engage_percent_success": 0.0,
            "tele_charge_attempts": 2,
            "tele_dock_successes": 0,
            "tele_dock_percent_success": 0.0,
            "tele_dock_only_percent_success": 0.0,
            "tele_engage_successes": 0,
            "tele_engage_percent_success": 0.0,
            "tele_park_successes": 1,
            "tele_park_percent_success": 0.5,
        },
        {
            "team_number": "1000",
            "matches_played": 5,
            "auto_avg_cube_low": 0.0,
            "auto_avg_cone_low": 0.0,
            "auto_avg_cube_mid": 0.0,
            "auto_avg_cone_mid": 0.0,
            "auto_avg_cube_high": 0.0,
            "auto_avg_cone_high": 0.0,
            "auto_avg_cube_total": 0.0,
            "auto_avg_cone_total": 0.0,
            "tele_avg_cube_low": 0.0,
            "tele_avg_cone_low": 0.0,
            "tele_avg_cube_mid": 0.0,
            "tele_avg_cone_mid": 0.0,
            "tele_avg_cube_high": 0.0,
            "tele_avg_cone_high": 0.0,
            "tele_avg_cube_total": 0.0,
            "tele_avg_cone_total": 0.0,
            "auto_charge_attempts": 0,
            "auto_dock_successes": 0,
            "auto_dock_percent_success": 0.0,
            "auto_dock_only_percent_success": 0.0,
            "auto_engage_successes": 0,
            "auto_engage_percent_success": 0.0,
            "tele_charge_attempts": 0,
            "tele_dock_successes": 0,
            "tele_dock_percent_success": 0.0,
            "tele_dock_only_percent_success": 0.0,
            "tele_engage_successes": 0,
            "tele_engage_percent_success": 0.0,
            "tele_park_successes": 0,
            "tele_park_percent_success": 0.0,
        },
    ]
    fake_tba_team_data = [
        {
            "team_number": "1678",
            "mobility_successes": 5,
        },
        {
            "team_number": "1533",
            "mobility_successes": 4,
        },
        {
            "team_number": "7229",
            "mobility_successes": 3,
        },
        {
            "team_number": "2468",
            "mobility_successes": 2,
        },
        {
            "team_number": "1000",
            "mobility_successes": 1,
        },
    ]
    expected_return = {
        "predicted_score": 280.83333,
        "predicted_grid_score": 250.3,
        "predicted_auto_score": 61.2,
        "predicted_charge_score": 22.0,
        "predicted_tele_score": 219.63333,
    }
    assert (
        predict_alliance(
            "1678", "1533", "7229", test_server, fake_obj_team_data, fake_tba_team_data
        )
        == expected_return
    )
